# Air configuration file (.air.toml)
root = "."
tmp_dir = "tmp"

[build]
# Comando para compilar tu aplicación
cmd = "go build -o ./tmp/main ."
# Binario a ejecutar
bin = "./tmp/main"
# Archivos a observar para cambios
include_ext = ["go", "tpl", "tmpl", "html"]
# Archivos a ignorar
exclude_dir = ["assets", "tmp", "vendor"]